{% set data = load_setup_py_data() %}

package:
  name: pyzebra
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  entry_points:
    - pyzebra = pyzebra.app.cli:main

requirements:
  build:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - h5py
    - bokeh =2.4
    - numba
    - lmfit >=1.0.2


about:
  home: https://github.com/paulscherrerinstitute/pyzebra
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
